title: <p align="center"> ALI RAHIMI </p>

logo: "/images/picture.jpg?raw=true"

description:
  
  <p align="justify">
  <b> Data Scientist and Quant </b>
  <br><br>
  Master's degree in Electrical Engineering from <a href="https://www.topuniversities.com/universities/amirkabir-university-technology"> Amirkabir University of Technology</a> (Graduated at top of the class).
  <br><br>
  </p>


  <p align="justify">
  <b> Professional Certificates </b>
  <br><br>
  <a href="https://www.credly.com/go/21MLbGJc"> IBM Data Science Professional Certificate</a>
  <a href="https://www.credly.com/go/GBRSgHVj"> IBM Machine Learning Professional Certificate</a>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
