title: <p align="center"> ALI RAHIMI </p>

logo: "/images/picture.jpg?raw=true"

description:
  
  <p align="justify">
  <b> Data Scientist and Quant </b>
  <br><br>
  Master's degree in Electrical Engineering from <a href="https://www.topuniversities.com/universities/amirkabir-university-technology"> Amirkabir University of Technology</a> (Graduated at top of the class).
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
